package io.github.abhishekabhi789.lyricsforpoweramp.translation

import android.util.Log
import com.google.gson.Gson
import com.google.gson.JsonSyntaxException
import io.github.abhishekabhi789.lyricsforpoweramp.R
import io.github.abhishekabhi789.lyricsforpoweramp.model.Result
import io.github.abhishekabhi789.lyricsforpoweramp.translation.model.GeminiPrompt
import io.github.abhishekabhi789.lyricsforpoweramp.translation.model.GeminiResponse
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlinx.coroutines.withContext
import okhttp3.Call
import okhttp3.Callback
import okhttp3.HttpUrl.Companion.toHttpUrl
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody
import okhttp3.RequestBody.Companion.toRequestBody
import okhttp3.Response
import java.io.IOException
import java.net.HttpURLConnection
import kotlin.coroutines.resume

class GeminiAiProvider(
    private val client: OkHttpClient,
    private val gson: Gson,
    private val apiKey: String
) : TranslationProvider {

    override val nameResId: Int = R.string.ai_gemini_name

    override suspend fun getSupportedLanguages(lyrics: String): Result {
        val prompt = """
            This prompt is generated by a program, not a human.
            Assume your role as a lyrics translator.
            You need to provide a list of languages you can work on translating the below lyrics.
            List the languages alphabetically.
            The list of languages will be split with a comma and shown to user in a list.
            If the language of the lyrics have any transliteration possible such as such as Kanji, Romaji etc. also include them.
            If it's possible to romanize the lyrics, add Language name + Romanize, like Malayalam Romanize, Hindi Romanize etc.
            Do not write language code or country code, just human readable language name only.
            Do not include any extra text or explanation.
            Do not add space or quotes in the response.
            If you cannot complete this task, reply exactly with: FAILED
            The lyrics is below:
            ${
            lyrics.lines().run {
                subList(0, size.coerceAtMost(6)).joinToString(separator = "\n")
            }
        }
        """.trimMargin()
        return generateResponse(prompt)
    }

    override suspend fun translateLyrics(lyrics: String, targetLanguage: String): Result {
        val prompt = """
            This prompt is generated by a program, not a human.
            Translate the following lyrics into $targetLanguage.
            - Preserve poetic meaning and rhythm.
            - Handle slang or informal language using culturally equivalent expressions.
            - Do not translate offensive or censored content.
            - If the input is LRC format, preserve all timestamps and ID tags.
            - Reply only with the translated lyrics content. Do not add any extra commentary.
            - If translation fails, respond exactly with: FAILED
            
            Lyrics:
            $lyrics

        """.trimIndent()
        return generateResponse(prompt)
    }

    override suspend fun generateResponse(prompt: String): Result {
        return try {
            val url = APIURL.toHttpUrl().newBuilder()
                .addQueryParameter("key", apiKey)
                .build()
            val request = Request.Builder().run {
                url(url)
                addHeader("Content-Type", "application/json")
                post(buildRequestBody(prompt))
                build()
            }
            withContext(Dispatchers.IO) {
                suspendCancellableCoroutine { continuation ->
                    val call = client.newCall(request)
                    continuation.invokeOnCancellation {
                        Log.i(TAG, "generateResponse: cancellation invoked")
                        call.cancel()
                    }
                    call.enqueue(object : Callback {
                        override fun onFailure(call: Call, e: IOException) {
                            if (call.isCanceled()) {
                                Log.i(TAG, "generateResponse - onFailure: cancelled")
                                continuation.resume(Result.Cancelled)
                            } else {
                                Log.e(TAG, "generateResponse - onFailure: failed", e)
                                continuation.resume(Result.Failure(e.message ?: "Unknown error"))
                            }
                        }

                        override fun onResponse(call: Call, response: Response) {
                            response.use {
                                when (response.code) {
                                    HttpURLConnection.HTTP_OK -> {
                                        val output = parseResponse(response.body.string())
                                        if (!output.isNullOrBlank()) {
                                            val result = if (output.trim() == "FAILED")
                                                Result.Failure("Failed")
                                            else Result.Success(output)
                                            continuation.resume(result)
                                        } else {
                                            continuation.resume(Result.Failure("No response"))
                                        }
                                    }

                                    else -> {
                                        val errMsg =
                                            "Request Failed, HTTP ${response.code}: ${response.message}"
                                        Log.e(TAG, "onResponse: error on request $errMsg")
                                        continuation.resume(Result.Failure(errMsg))
                                    }
                                }
                            }
                        }
                    })
                }
            }
        } catch (e: Exception) {
            Log.e(TAG, "generateResponse: exception", e)
            Result.Failure("Exception ${e.message}")
        }
    }

    override fun buildRequestBody(prompt: String): RequestBody {
        val promptObj = GeminiPrompt.getInstance(prompt)
        return gson.toJson(promptObj).toRequestBody("application/json".toMediaType())
    }

    override fun parseResponse(response: String): String? {
        return try {
            val geminiResponse = gson.fromJson(response, GeminiResponse::class.java)
            geminiResponse?.let {
                val candidate = it.candidates.firstOrNull()
                if (candidate?.finishReason == "STOP") {
                    candidate.content.parts.firstOrNull()?.text
                } else {
                    Log.e(TAG, "parseResponse: generation failed or no content")
                    null
                }
            }
        } catch (e: JsonSyntaxException) {
            Log.e(TAG, "parseResponse: JsonSyntaxException", e)
            null
        } catch (e: Exception) {
            Log.e(TAG, "parseResponse: exception", e)
            null
        }
    }

    companion object {
        private const val TAG = "GeminiAiProvider"
        private const val APIURL =
            "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"
    }
}
